project_name: pbcli

builds:
  - id: pbcli
    main: ./cmd/pbcli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

checksum:
  algorithm: sha256

archives:
  - id: pbcli
    builds:
      - pbcli
    format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
