project_name: pbcli

builds:
  - id: pbcli
    main: ./cmd/pbcli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/pushbits/cli/internal/buildconfig.Version=v{{.Version}}

checksum:
  algorithm: sha256

archives:
  - id: pbcli
    builds:
      - pbcli
    format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
